/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturarloswsdl;



/**
 *
 * @author Apipiltzin
 */
public class frmTest extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public frmTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mmRespuesta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mmRespuestaXML = new javax.swing.JTextArea();
        edtFacturaIn = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        edtNumAutorizacionUUID = new javax.swing.JTextField();
        edtMotivoAnulacion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMotivoAnulacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mmRespuesta.setColumns(20);
        mmRespuesta.setRows(5);
        jScrollPane1.setViewportView(mmRespuesta);

        jButton1.setText("Firmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mmRespuestaXML.setColumns(20);
        mmRespuestaXML.setRows(5);
        jScrollPane2.setViewportView(mmRespuestaXML);

        edtFacturaIn.setText("./InputFiles/fact.xml");

        jButton2.setText("Anular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        edtNumAutorizacionUUID.setText("80D28890-D186-437B-9AA6-CAD483A2AFFB");

        edtMotivoAnulacion.setText("Probando anulación de factura");
        edtMotivoAnulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtMotivoAnulacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Datos de facturación");

        jLabel2.setText("NumAutorizacionUUID");

        lblMotivoAnulacion.setText("MotivoAnulacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtFacturaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(edtNumAutorizacionUUID, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMotivoAnulacion)
                                    .addComponent(edtMotivoAnulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2))
                        .addGap(196, 196, 196)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lblMotivoAnulacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFacturaIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtNumAutorizacionUUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtMotivoAnulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        FacturarlosWSDL ClienteWSDL = new FacturarlosWSDL();
        
        /******************************************************/
        /*** true -> Firma en producción **********************/
        ClienteWSDL.setEsProduccion(false);
        /******************************************************/
        /******************************************************/
        
        ClienteWSDL.setXmldocInFilePath(edtFacturaIn.getText()); // "./InputFiles/fact.xml"
        ClienteWSDL.setOutputXmlPDFPath("./OutputFiles/"); 
        
        ResultWSDL ResultFirma = ClienteWSDL.Execute_Firma();
        
        mmRespuesta.setText("");
        mmRespuesta.append(String.valueOf((  ResultFirma.getCodigoResp() )));
        mmRespuesta.append("\n"+             ResultFirma.getTextoResp()  );
        
        mmRespuestaXML.append(     "----------------------------------");
        mmRespuestaXML.append("\n"+"------- FIRMANDO ----------");
        mmRespuestaXML.append("\n"+"----------------------------------");
        mmRespuestaXML.append( "\n"+"FechaEmision: \t \t" +          ResultFirma.getFechaEmision() );
        mmRespuestaXML.append( "\n"+"FechaCertificacion: \t" +  ResultFirma.getFechaCertificacion() );
        mmRespuestaXML.append( "\n"+"NumeroAutorizacion: \t" +  ResultFirma.getNumeroAutorizacion() );
        mmRespuestaXML.append( "\n"+"Serie: \t \t" +            ResultFirma.getSerie() );
        mmRespuestaXML.append( "\n"+"Numero: \t \t" +           ResultFirma.getNumero() );
        mmRespuestaXML.append( "\n"+"PathXmlFile: \t \t" +      ResultFirma.getPathXmlFile() );
        mmRespuestaXML.append( "\n"+"PathPdfFile: \t \t" +      ResultFirma.getPathPdfFile() );
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        FacturarlosWSDL ClienteWSDL = new FacturarlosWSDL();
        
        /******************************************************/
        /*** true -> Anula en producción **********************/
        ClienteWSDL.setEsProduccion(false);
        /******************************************************/
        /******************************************************/
        
        
        
        ClienteWSDL.setNumAutorizacionUuid(edtNumAutorizacionUUID.getText() );
        ClienteWSDL.setMotivoAnulacion(edtMotivoAnulacion.getText());
        
        ClienteWSDL.setOutputXmlPDFPath("./OutputFilesAnulacion/"); 
        
        ResultWSDL ResultAnulacion = ClienteWSDL.Execute_Anulacion();
        
        mmRespuesta.setText("");
        
        mmRespuesta.append(String.valueOf((  ResultAnulacion.getCodigoResp() )));
        mmRespuesta.append("\n"+             ResultAnulacion.getTextoResp()  );
        
        mmRespuestaXML.append("\n"+"----------------------------------");
        mmRespuestaXML.append("\n"+"------- ANULANDO ---------");
        mmRespuestaXML.append("\n"+"----------------------------------"); 
        mmRespuestaXML.append("\n"+"FechaAnulacion: \t" +        ResultAnulacion.getFechaAnulacion() );
        mmRespuestaXML.append("\n"+"FechaCertificacion: \t" +  ResultAnulacion.getFechaCertificacion() );

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void edtMotivoAnulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtMotivoAnulacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtMotivoAnulacionActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField edtFacturaIn;
    private javax.swing.JTextField edtMotivoAnulacion;
    private javax.swing.JTextField edtNumAutorizacionUUID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMotivoAnulacion;
    private javax.swing.JTextArea mmRespuesta;
    private javax.swing.JTextArea mmRespuestaXML;
    // End of variables declaration//GEN-END:variables


}
